# Generated by Django 2.2.6 on 2020-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leidoscloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="ticker_symbol",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
