# Generated by Django 2.1.7 on 2020-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leidoscloud", "0002_api_ticker_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="sys_vendor_search_string",
            field=models.CharField(
                help_text="The current host is identified by reading /sys/devices/virtual/dmi/id/sys_vendor. Please enter a unique string which appears in this file when running on this cloud host.",
                max_length=10,
                null=True,
            ),
        ),
    ]
