# Generated by Django 2.2.6 on 2020-02-24 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("leidoscloud", "0004_prediction_stockdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 2, 24, 10, 37, 14, 978085, tzinfo=utc)
            ),
        ),
    ]
